steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true

  - trailing_whitespace: {}

columns: 80

newline: native

language_extensions:
  - NoImplicitPrelude
  - StrictData
  - BangPatterns
  - LambdaCase
  - TupleSections
  - PatternSynonyms
  - RecordWildCards
  - ViewPatterns
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveGeneric
  - DeriveDataTypeable
  - EmptyDataDecls
  - DataKinds
  - PolyKinds
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - RoleAnnotations
  - GADTs
  - ExistentialQuantification
  - TypeFamilyDependencies
  - FunctionalDependencies
  - ScopedTypeVariables
  - FlexibleContexts
  - RankNTypes
  - ConstraintKinds
  - MultiParamTypeClasses
