name:        satt-composition
version:     '0.1.0.0'
synopsis:    Implementation of SATT Composition
description: SATT Composition implementation
category:    Tree
author:      Mizunashi Mana
maintainer:  mizunashi-mana@noreply.git
copyright:   2017 Mizunashi Mana
license:     MIT
homepage:    https://gitlab.com/mizunashi-mana/satt-composition#readme
git:         https://gitlab.com/mizunashi-mana/satt-composition
extra-source-files:
- README.md

build-type: Custom

# unsupported
# cabal-version: '>=2.0.0.0'

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest

library:
  ghc-options:
  - -Wall
  source-dirs: src
  default-extensions:
  - NoImplicitPrelude
  - StrictData
  - BangPatterns
  - LambdaCase
  - TupleSections
  - PatternSynonyms
  - RecordWildCards
  - ViewPatterns
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveGeneric
  - DeriveDataTypeable
  - EmptyDataDecls
  - DataKinds
  - PolyKinds
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - RoleAnnotations
  - GADTs
  - ExistentialQuantification
  - TypeFamilyDependencies
  - FunctionalDependencies
  - ScopedTypeVariables
  - FlexibleContexts
  - RankNTypes
  - ConstraintKinds
  exposed-modules:
  - Data.Universe.Instances
  - Data.TypeLevel.TaggedEither
  - Data.Pattern.Error
  - Data.Tree.RankedTree
  - Data.Tree.RankedTree.Instances
  - Data.Tree.RankedTree.Zipper
  - Data.Tree.Trans.Class
  - Data.Tree.Trans.ATT
  - Data.Tree.Trans.ATT.Instances
  - Data.Tree.Trans.ATT.Compose
  - Data.Tree.Trans.SATT
  #- Data.Tree.Trans.SATT.Instances
  #- Data.Tree.Trans.SATT.Compose
  #- Data.Tree.Trans.Demo
  other-modules: []
  dependencies:
  - base >=4.7 && <5
  - classy-prelude
  - lens
  - mono-traversable
  - vector
  - profunctors
  - constraints
  - universe-base

executables:
  satt-composit:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - NoImplicitPrelude
    - TypeFamilies
    - GADTs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - classy-prelude
    - satt-composition

tests:
  lint:
    main: Lint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -Wall
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - hlint

  spec-test:
    main: ../Spec.hs
    source-dirs: test/specs
    ghc-options:
    - -Wall
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - classy-prelude
    - satt-composition
    - hspec
    - QuickCheck
    default-extensions:
    - NoImplicitPrelude

  doc-test:
    main: Doctest.hs
    source-dirs: test
    other-modules:
    - Build_doctests
    ghc-options:
    - -Wall
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - doctest

benchmarks:
  common:
    main: Common.hs
    source-dirs: benchmark
    ghc-options:
    - -Wall
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - base
    - satt-composition
    - criterion
