name:        smtt-composition
version:     '0.2.0.0'
synopsis:    Implementation of SMTT Composition
description: SMTT Composition implementation
category:    Tree
author:      Nishiyama Shun
maintainer:  nishiyama@ipl.cs.uec.ac.jp
copyright:   2018 Nishiyama Shun
license:     MIT
homepage:    https://github.com/shnishiyama/satt-composition
git:         https://github.com/shnishiyama/satt-composition

extra-source-files:
- README.md

_base-depends: &base-depends
  base: '>=4.7 && <5'
  satt-prelude:

build-type: Custom
custom-setup:
  dependencies:
    <<: *base-depends
    Cabal: '>= 2.0'
    cabal-doctest:

ghc-options:
  - -Wall
  # for GHC 8.2.x bugs... (disable only executable/tests)
  #- -dcore-lint
  - -fmax-pmcheck-iterations=1000000
  - -funbox-strict-fields

default-extensions:
  # use satt-prelude
  - NoImplicitPrelude

  # performance supports
  - BangPatterns
  - EmptyCase
  - StrictData

  # useful syntaxes
  - Arrows
  - BinaryLiterals
  - DefaultSignatures
  # for Cabal 2.0.x
  #- DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - PatternSynonyms
  - RecordWildCards
  - RecursiveDo
  - StandaloneDeriving
  - TupleSections
  - ViewPatterns

  # useful derivable
  - GeneralizedNewtypeDeriving
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DeriveAnyClass

  # extensions of type systems
  - ConstraintKinds
  - DataKinds
  - FunctionalDependencies
  - GADTs
  - PolyKinds
  - RankNTypes
  - RoleAnnotations
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  exposed-modules:
    # utilities
    - Data.Bifunctor.FixLR
    - Text.PrettyPrint.Classy

    # ranked tree
    - Data.Tree.RankedTree
    - Data.Tree.RankedTree.Instances
    - Data.Tree.RankedTree.Label
    - Data.Tree.RankedTree.Zipper

    # tree transducers
    - Data.Tree.Trans.Class
    - Data.Tree.Trans.TOP
    - Data.Tree.Trans.TOP.Instances
    - Data.Tree.Trans.MAC
    - Data.Tree.Trans.MAC.Instances
    - Data.Tree.Trans.ATT
    - Data.Tree.Trans.ATT.Instances
    - Data.Tree.Trans.Stack
    - Data.Tree.Trans.SATT
    - Data.Tree.Trans.SATT.Instances
    - Data.Tree.Trans.SMAC
    - Data.Tree.Trans.SMAC.Instances

    # compose/decompose tree transducers
    - Data.Tree.Trans.Compose.Desc
    - Data.Tree.Trans.Compose.ExtendDesc
    - Data.Tree.Trans.Compose.TdttAndSmtt
    - Data.Tree.Trans.Compose.ExtendVoigt2004
    - Data.Tree.Trans.Decompose.MttToAtt
    - Data.Tree.Trans.Decompose.SmttToSatt

    # haskell generator
    - Language.Haskell.Encoding
    - Language.Haskell.Tree.Trans.SMAC
  other-modules: []
  ghc-options:
  - -dcore-lint
  dependencies:
    <<: *base-depends
    unordered-containers:
    vector:
    singletons:
    mtl:
    ansi-wl-pprint:
    data-reify:
    text:

executables:
  satt-composit:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    ghc-prof-options:
    - -threaded
    - -rtsopts
    - -eventlog
    - "\"-with-rtsopts=-N -xc\""
    dependencies:
      <<: *base-depends
      smtt-composition:
      deepseq:

tests:
  lint:
    main: Lint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      <<: *base-depends
      hlint:

  spec-test:
    main: Spec.hs
    source-dirs: test/specs
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      <<: *base-depends
      smtt-composition:
      hspec:
      QuickCheck:

  doc-test:
    main: Doctest.hs
    source-dirs: test
    other-modules:
    - Build_doctests
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      <<: *base-depends
      doctest:
      QuickCheck:
      template-haskell:

_bench-base-depends: &bench-base-depends
  <<: *base-depends
  criterion:
  weigh:
  deepseq:
  random:
  mtl:

_bench-ghc-options: &bench-ghc-options
  - -O0
  - -threaded
  - -with-rtsopts=-N

benchmarks:
  common:
    main: ../Common.hs
    source-dirs: benchmark/lib
    ghc-options: *bench-ghc-options
    dependencies:
      <<: *bench-base-depends

  fusion-speed-bench:
    main: ../CriterionFusionMain.hs
    source-dirs: benchmark/lib
    ghc-options: *bench-ghc-options
    dependencies:
      <<: *bench-base-depends

  fusion-memory-bench:
    main: ../WeighFusionMain.hs
    source-dirs: benchmark/lib
    ghc-options: *bench-ghc-options
    dependencies:
      <<: *bench-base-depends
