name:        satt-composition
version:     '0.1.0.0'
synopsis:    Implementation of SATT Composition
description: SATT Composition implementation
category:    Tree
author:      Mizunashi Mana
maintainer:  mizunashi-mana@noreply.git
copyright:   2017 Mizunashi Mana
license:     MIT
homepage:    https://gitlab.com/mizunashi-mana/satt-composition#readme
git:         https://gitlab.com/mizunashi-mana/satt-composition
extra-source-files:
- README.md

# unsupported by hpack
# cabal-version: '>=2.0.0.0'

# unsupported by hpack bundled latest stack
#base-dependencies:
#  base: '>=4.7 && <5'
#  classy-prelude:

dependencies:
  - base >=4.7 && <5
  - classy-prelude

# unsupported by hpack
#base-ghc-options:
#  -Wall:
#  -fprint-explicit-foralls:
#  -dcore-lint:
#  -fmax-pmcheck-iterations: '5000000'
#  -funbox-strict-fields:

ghc-options:
  - -Wall
  - -fprint-explicit-foralls
  - -dcore-lint
  - -fmax-pmcheck-iterations=5000000
  - -funbox-strict-fields

default-extensions:
  # use classy-prelude
  - NoImplicitPrelude

  # performance supports
  - BangPatterns
  - StrictData
  - ApplicativeDo

  # useful syntaxes
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - TupleSections
  - RecordWildCards
  - ViewPatterns
  - PatternSynonyms
  - StandaloneDeriving
  - BinaryLiterals

  # useful derivable
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - DeriveDataTypeable

  # extensions of type systems
  - DataKinds
  - PolyKinds
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - RoleAnnotations
  - GADTs
  - ExistentialQuantification
  - TypeFamilyDependencies
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - ConstraintKinds

build-type: Custom
custom-setup:
  dependencies:
    - base
    - classy-prelude
    - Cabal
    - cabal-doctest

library:
  source-dirs: src
  exposed-modules:
  - Control.Universe
  - Data.Universe.Instances
  - Data.TypeLevel.TaggedEither
  - Data.Pattern.Error
  - Data.Tree.RankedTree
  - Data.Tree.RankedTree.Instances
  - Data.Tree.RankedTree.Zipper
  - Data.Tree.Trans.Class
  - Data.Tree.Trans.TOP
  - Data.Tree.Trans.ATT
  - Data.Tree.Trans.ATT.Instances
  - Data.Tree.Trans.ATT.Compose
  #- Data.Tree.Trans.SATT
  #- Data.Tree.Trans.SATT.Instances
  #- Data.Tree.Trans.SATT.Compose
  #- Data.Tree.Trans.Demo
  other-modules: []
  dependencies:
  - lens
  - mono-traversable
  - vector
  - profunctors
  - constraints
  - universe-base
  - keys
  - unordered-containers

executables:
  satt-composit:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - satt-composition
    - deepseq

tests:
  lint:
    main: Lint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hlint

  spec-test:
    main: ../Spec.hs
    source-dirs: test/specs
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - satt-composition
    - hspec
    - QuickCheck

  doc-test:
    main: Doctest.hs
    source-dirs: test
    other-modules:
    - Build_doctests
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - QuickCheck
    - template-haskell

benchmarks:
  common:
    main: Common.hs
    source-dirs: benchmark
    ghc-options:
    - -O2
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - satt-composition
    - criterion
    - deepseq
